version: '3.8'

services:
  mongo:
    image: mongo
    container_name: shoppingweb_mongo
    ports:
      - "27017:27017" # Puerto de MongoDB
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: shoppingweb_redis
    ports:
      - "6379:6379"  # Puerto para Redis

volumes:
  mongo_data:
