version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: shoppingweb_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shoppingweb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: shoppingweb_redis
    ports:
      - "6379:6379"  # Puerto para Redis

volumes:
  db_data: